CREATE TABLE T_0006 (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    VALUE NUMBER,
    STATUS VARCHAR2(20),
    CREATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT T_0006_KEY CHECK (VALUE > 0 AND STATUS IN ('ACTIVE', 'INACTIVE', 'PENDING'))
);
