-- テーブルの作成
CREATE TABLE T_0013 (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(100),
    PHONE_NUMBER VARCHAR2(20),
    HIRE_DATE DATE,
    JOB_ID VARCHAR2(10),
    SALARY NUMBER(8,2),
    COMMISSION_PCT NUMBER(2,2),
    MANAGER_ID NUMBER,
    DEPARTMENT_ID NUMBER
);

-- 読み取り専用ビューの作成
CREATE OR REPLACE VIEW T_0013_VIEW
AS
SELECT
    EMPLOYEE_ID,
    FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID,
    DEPARTMENT_ID,
    CASE
        WHEN DEPARTMENT_ID = 10 THEN '総務部'
        WHEN DEPARTMENT_ID = 20 THEN '営業部'
        WHEN DEPARTMENT_ID = 30 THEN '開発部'
        WHEN DEPARTMENT_ID = 40 THEN '人事部'
        ELSE '未所属'
    END AS DEPARTMENT_NAME,
    ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE) / 12, 1) AS YEARS_OF_SERVICE
FROM
    T_0013
WITH READ ONLY;
