-- テーブルの作成
CREATE TABLE T_0022 (
    ID NUMBER PRIMARY KEY,
    XML_DATA XMLTYPE
);

CREATE OR REPLACE PROCEDURE SCT_0022_XMLSEQUECE
IS
	v_xml XMLSEQUENCETYPE;
BEGIN
	SELECT XMLSEQUENCE(EXTRACT(xml_data, '/EMPLOYEES/*'))
	INTO v_xml
	FROM T_0022
	WHERE id = 1;
END;
/
