CREATE TABLE T_0028_DOCUMENTS (
    DOC_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200),
    AUTHOR VARCHAR2(100),
    DOC_TEXT CLOB,
    LAST_UPDATE DATE
);

-- プリファレンスの作成（オプション）
BEGIN
    CTX_DDL.CREATE_PREFERENCE('T_0028_LEXER', 'JAPANESE_VGRAM_LEXER');
END;
/

-- CONTEXTドメインインデックスの作成
CREATE INDEX T_0028_TEXT_IDX ON T_0028_DOCUMENTS(DOC_TEXT)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS ('LEXER T_0028_LEXER');
