-- テーブルの作成
CREATE TABLE T_0031 (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    VALUE NUMBER,
    STATUS VARCHAR2(20),
    LAST_UPDATED DATE
);

-- REFERENCING句を使用したトリガーの作成
CREATE OR REPLACE TRIGGER T_0031_TRIGGER
BEFORE UPDATE ON T_0031
REFERENCING OLD AS OLD_DATA NEW AS NEW_DATA
FOR EACH ROW
BEGIN
    -- 値が変更された場合のみログを記録
    IF :OLD_DATA.VALUE != :NEW_DATA.VALUE THEN
        DBMS_OUTPUT.PUT_LINE('値が変更されました:');
        DBMS_OUTPUT.PUT_LINE('ID: ' || :OLD_DATA.ID);
        DBMS_OUTPUT.PUT_LINE('旧値: ' || :OLD_DATA.VALUE);
        DBMS_OUTPUT.PUT_LINE('新値: ' || :NEW_DATA.VALUE);

        -- ステータスも更新
        IF :NEW_DATA.VALUE > :OLD_DATA.VALUE THEN
            :NEW_DATA.STATUS := 'INCREASED';
        ELSE
            :NEW_DATA.STATUS := 'DECREASED';
        END IF;

        -- 最終更新日時を設定
        :NEW_DATA.LAST_UPDATED := SYSDATE;
    END IF;
END;
/
