CREATE USER &1 IDENTIFIED BY &2;

-- 必要な権限の付与
GRANT CREATE SESSION TO &&1;
GRANT CREATE TRIGGER TO &&1;
GRANT CREATE PROCEDURE TO &&1;

-- シンプルなテーブルの作成
CREATE TABLE T_0032 (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    VALUE NUMBER,
    CREATED_DATE DATE DEFAULT SYSDATE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON T_0032 TO &&1;

-- トリガーの作成
CREATE OR REPLACE TRIGGER &&1.T_0032_TRIGGER
AFTER INSERT OR UPDATE OR DELETE ON T_0032
FOR EACH ROW
BEGIN
    -- INSERTの場合
    IF INSERTING THEN
        DBMS_OUTPUT.PUT_LINE('INSERT操作が実行されました。ID: ' || :NEW.ID || ', NAME: ' || :NEW.NAME);

    -- UPDATEの場合
    ELSIF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('UPDATE操作が実行されました。');
        DBMS_OUTPUT.PUT_LINE('  変更前 - ID: ' || :OLD.ID || ', NAME: ' || :OLD.NAME || ', VALUE: ' || :OLD.VALUE);
        DBMS_OUTPUT.PUT_LINE('  変更後 - ID: ' || :NEW.ID || ', NAME: ' || :NEW.NAME || ', VALUE: ' || :NEW.VALUE);

    -- DELETEの場合
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('DELETE操作が実行されました。ID: ' || :OLD.ID || ', NAME: ' || :OLD.NAME);

    END IF;
END;
/
