CREATE TABLE T_0034 (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    VALUE NUMBER,
    CREATED_DATE DATE DEFAULT SYSDATE
);

CREATE OR REPLACE VIEW T_0034_VIEW AS
SELECT ID, NAME, VALUE, CREATED_DATE
FROM T_0034;

-- 元のテーブルの構造を変更してビューをINVALIDにする
ALTER TABLE T_0034 DROP COLUMN VALUE;
