-- テーブルの作成
CREATE TABLE T_0035 (
    ID NUMBER,
    NAME VARCHAR2(100),
    VALUE NUMBER,
    CREATED_DATE DATE DEFAULT SYSDATE
);

-- 主キー制約をDISABLE状態で作成
ALTER TABLE T_0035 ADD CONSTRAINT PK_T_0035
PRIMARY KEY (ID) DISABLE;

-- 一意制約をDISABLE状態で作成
ALTER TABLE T_0035 ADD CONSTRAINT UQ_T_0035_NAME
UNIQUE (NAME) DISABLE;

-- CHECK制約をDISABLE状態で作成
ALTER TABLE T_0035 ADD CONSTRAINT CK_T_0035_VALUE
CHECK (VALUE > 0) DISABLE;

-- 外部キー用の参照テーブルを作成
CREATE TABLE T_0035_REF (
    REF_ID NUMBER PRIMARY KEY,
    REF_NAME VARCHAR2(100)
);

-- 外部キー制約をDISABLE状態で作成
ALTER TABLE T_0035 ADD CONSTRAINT FK_T_0035_REF_ID
FOREIGN KEY (ID) REFERENCES T_0035_REF(REF_ID) DISABLE;

-- DISABLE状態のトリガーを作成
CREATE OR REPLACE TRIGGER SCT_0035_TRIGGER
AFTER INSERT OR UPDATE OR DELETE ON T_0035
FOR EACH ROW
DISABLE  -- トリガーを無効化
BEGIN
    -- INSERTの場合
    IF INSERTING THEN
        DBMS_OUTPUT.PUT_LINE('レコードが挿入されました。ID: ' || :NEW.ID);

    -- UPDATEの場合
    ELSIF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('レコードが更新されました。ID: ' || :NEW.ID);

    -- DELETEの場合
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('レコードが削除されました。ID: ' || :OLD.ID);

    END IF;
END;
/
