-- Primary Keyのない、LOB型を持つテーブルの作成
CREATE TABLE T_0066 (
    ID NUMBER,
    NAME VARCHAR2(100),
    DESCRIPTION CLOB,
    DOCUMENT BLOB,
    IMAGE_DATA BLOB,
    XML_DATA XMLTYPE,
    CREATED_DATE DATE DEFAULT SYSDATE
);
